from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GradingWindow(object):
    def setup_ui(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 675)
        MainWindow.setStyleSheet(open('style.qss', 'r').read())
        MainWindow.setWindowTitle("Orange Grader")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 800, 630))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title_label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.title_label_3.setMinimumSize(QtCore.QSize(270, 100))
        self.title_label_3.setMaximumSize(QtCore.QSize(270, 100))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.title_label_3.setFont(font)
        self.title_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label_3.setObjectName("title_label_3")
        self.horizontalLayout.addWidget(self.title_label_3)
        self.instructions_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.instructions_label.setMinimumSize(QtCore.QSize(450, 20))
        self.instructions_label.setMaximumSize(QtCore.QSize(270, 50))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.instructions_label.setFont(font)
        self.instructions_label.setTextFormat(QtCore.Qt.PlainText)
        self.instructions_label.setAlignment(QtCore.Qt.AlignCenter)
        self.instructions_label.setWordWrap(True)
        self.instructions_label.setObjectName("instructions_label")
        self.horizontalLayout.addWidget(self.instructions_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        self.btn_first_img = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_first_img.setMinimumSize(QtCore.QSize(250, 0))
        self.btn_first_img.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.btn_first_img.setFont(font)
        self.btn_first_img.setAutoFillBackground(False)
        self.btn_first_img.setObjectName("btn_first_img")
        self.gridLayout.addWidget(self.btn_first_img, 1, 0, 1, 1)
        self.btn_second_img = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_second_img.setMinimumSize(QtCore.QSize(250, 0))
        self.btn_second_img.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.btn_second_img.setFont(font)
        self.btn_second_img.setObjectName("btn_second_img")
        self.gridLayout.addWidget(self.btn_second_img, 5, 0, 1, 1)
        self.pixmap_img_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixmap_img_1.sizePolicy().hasHeightForWidth())
        self.pixmap_img_1.setSizePolicy(sizePolicy)
        self.pixmap_img_1.setMinimumSize(QtCore.QSize(250, 200))
        self.pixmap_img_1.setMaximumSize(QtCore.QSize(250, 200))
        self.pixmap_img_1.setAutoFillBackground(False)
        self.pixmap_img_1.setText("")
        self.pixmap_img_1.setObjectName("pixmap_img_1")
        self.gridLayout.addWidget(self.pixmap_img_1, 0, 0, 1, 1)
        self.pixmap_mask_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.pixmap_mask_2.setMinimumSize(QtCore.QSize(250, 200))
        self.pixmap_mask_2.setMaximumSize(QtCore.QSize(250, 200))
        self.pixmap_mask_2.setText("")
        self.pixmap_mask_2.setObjectName("pixmap_mask_2")
        self.gridLayout.addWidget(self.pixmap_mask_2, 4, 1, 1, 1)
        self.pixmap_result_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixmap_result_1.sizePolicy().hasHeightForWidth())
        self.pixmap_result_1.setSizePolicy(sizePolicy)
        self.pixmap_result_1.setMinimumSize(QtCore.QSize(250, 200))
        self.pixmap_result_1.setMaximumSize(QtCore.QSize(250, 200))
        self.pixmap_result_1.setText("")
        self.pixmap_result_1.setObjectName("pixmap_result_1")
        self.gridLayout.addWidget(self.pixmap_result_1, 0, 2, 1, 1)
        self.pixmap_mask_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixmap_mask_1.sizePolicy().hasHeightForWidth())
        self.pixmap_mask_1.setSizePolicy(sizePolicy)
        self.pixmap_mask_1.setMinimumSize(QtCore.QSize(250, 200))
        self.pixmap_mask_1.setMaximumSize(QtCore.QSize(250, 200))
        self.pixmap_mask_1.setText("")
        self.pixmap_mask_1.setObjectName("pixmap_mask_1")
        self.gridLayout.addWidget(self.pixmap_mask_1, 0, 1, 1, 1)
        self.defect_area_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.defect_area_label.setFont(font)
        self.defect_area_label.setObjectName("defect_area_label")
        self.gridLayout.addWidget(self.defect_area_label, 7, 1, 1, 1)
        self.grade_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.grade_label.setFont(font)
        self.grade_label.setObjectName("grade_label")
        self.gridLayout.addWidget(self.grade_label, 7, 2, 1, 1)
        self.pixmap_img_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.pixmap_img_2.setMinimumSize(QtCore.QSize(250, 200))
        self.pixmap_img_2.setMaximumSize(QtCore.QSize(250, 200))
        self.pixmap_img_2.setText("")
        self.pixmap_img_2.setObjectName("pixmap_img_2")
        self.gridLayout.addWidget(self.pixmap_img_2, 4, 0, 1, 1)
        self.pixmap_result_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.pixmap_result_2.setMinimumSize(QtCore.QSize(250, 200))
        self.pixmap_result_2.setMaximumSize(QtCore.QSize(250, 200))
        self.pixmap_result_2.setText("")
        self.pixmap_result_2.setObjectName("pixmap_result_2")
        self.gridLayout.addWidget(self.pixmap_result_2, 4, 2, 1, 1)
        self.btn_grade = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_grade.setMinimumSize(QtCore.QSize(250, 0))
        self.btn_grade.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.btn_grade.setFont(font)
        self.btn_grade.setObjectName("btn_grade")
        self.gridLayout.addWidget(self.btn_grade, 7, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.title_label_3.setText(_translate("MainWindow", "Orange Grader"))
        self.instructions_label.setText(_translate("MainWindow", "Capture two pictures of the specimen using the buttons below. Then grade the images using the \'Grade Specimen\' button. "))
        self.btn_first_img.setText(_translate("MainWindow", "Take First Image"))
        self.btn_second_img.setText(_translate("MainWindow", "Take Second Image"))
        self.defect_area_label.setText(_translate("MainWindow", "Percentage Damaged:"))
        self.grade_label.setText(_translate("MainWindow", "Grade of Specimen:"))
        self.btn_grade.setText(_translate("MainWindow", "Grade Specimen"))

